apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: acrcalle.azurecr.io/samples/nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
